"""Trains the FS-15/16/17 grid-state Random Forest and saves it to
MODEL_PATH (see decision_layer.py) - once that file exists,
classify_grid_state() picks it up automatically, no code changes needed.

BLOCKED on real Simulink data. This has been run end-to-end against the
synthetic dataset generated by make_synthetic_data() below, to prove the
save/load/predict path actually works - the only missing piece is
swapping in the real CSV once your teammate provides it.

Usage once you have real data:
    python train_decision_model.py path/to/simulink_export.csv

Expected CSV columns (must match build_feature_vector's output keys in
decision_layer.py - regenerate this list if that function changes):
    system_anomaly_score, soc,
    <load_id>_anomaly_score, <load_id>_connected, <load_id>_critical
        for load_id in critical_1, critical_2, critical_3,
                        noncritical_1, noncritical_2
    grid_state   <- label column: normal/warning/critical/fault_imminent/islanded
"""

import os
import sys

import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, recall_score
from sklearn.model_selection import train_test_split

sys.path.insert(0, os.path.dirname(__file__))
from decision_layer import MODEL_PATH, LoadSignal, build_feature_vector  # noqa: E402

LOAD_IDS = ["critical_1", "critical_2", "critical_3", "noncritical_1", "noncritical_2"]
FEATURE_NAMES = sorted(
    build_feature_vector(
        system_anomaly_score=0.0,
        loads=[LoadSignal(lid, 0.0, True, True) for lid in LOAD_IDS],
        soc=0.0,
    ).keys()
)

# NFS-6 (essential): >=90% recall specifically on critical/fault_imminent -
# per the design doc, these gate whether the decision layer is trusted to
# drive real hardware. NFS-7 (non-essential): >=85% overall accuracy.
NFS6_TARGET_RECALL = 0.90
NFS6_STATES = ["critical", "fault_imminent"]
NFS7_TARGET_ACCURACY = 0.85


def make_synthetic_data(n=2000, seed=0):
    """Placeholder generator so this script is runnable/testable before
    real Simulink data exists. Mirrors the same threshold logic as the
    rule-based fallback, plus noise - delete once real data arrives."""
    import numpy as np
    rng = np.random.default_rng(seed)
    rows = []
    for _ in range(n):
        score = rng.uniform(0, 1)
        soc = rng.uniform(0, 1)
        row = {"system_anomaly_score": score, "soc": soc}
        for lid in LOAD_IDS:
            row[f"{lid}_anomaly_score"] = min(1.0, max(0.0, score + rng.normal(0, 0.1)))
            row[f"{lid}_connected"] = 1
            row[f"{lid}_critical"] = int(lid.startswith("critical"))
        noisy_score = min(1.0, max(0.0, score + rng.normal(0, 0.03)))
        if noisy_score < 0.2:
            state = "normal"
        elif noisy_score < 0.4:
            state = "warning"
        elif noisy_score < 0.6:
            state = "critical"
        elif noisy_score < 0.8:
            state = "fault_imminent"
        else:
            state = "islanded"
        row["grid_state"] = state
        rows.append(row)
    return pd.DataFrame(rows)


def train(df: pd.DataFrame):
    missing = set(FEATURE_NAMES) - set(df.columns)
    if missing:
        raise ValueError(f"CSV is missing expected columns: {sorted(missing)}")

    X = df[FEATURE_NAMES]
    y = df["grid_state"]
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

    model = RandomForestClassifier(n_estimators=200, max_depth=None, random_state=42, class_weight="balanced")
    model.fit(X_train, y_train)

    y_pred = model.predict(X_val)
    print(classification_report(y_val, y_pred))

    recalls = recall_score(y_val, y_pred, labels=NFS6_STATES, average=None, zero_division=0)
    accuracy = model.score(X_val, y_val)

    print(f"Overall accuracy: {accuracy:.3f} (NFS-7 target: >= {NFS7_TARGET_ACCURACY})")
    for state, recall in zip(NFS6_STATES, recalls):
        flag = "OK" if recall >= NFS6_TARGET_RECALL else "BELOW TARGET"
        print(f"Recall on '{state}': {recall:.3f} (NFS-6 target: >= {NFS6_TARGET_RECALL}) [{flag}]")

    if any(r < NFS6_TARGET_RECALL for r in recalls):
        print(
            "\nNFS-6 not met - per the risk assessment, this model will NOT be saved/"
            "deployed. Keeping the rule-based fallback active. Retrain with more data "
            "or better features, or re-run with --force to override (not recommended - "
            "this gates whether the decision layer is trusted to drive Critical Load 1)."
        )
        return model, False

    return model, True


def save_model(model):
    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    joblib.dump({"model": model, "feature_names": FEATURE_NAMES}, MODEL_PATH)
    print(f"Saved to {MODEL_PATH}")


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a != "--force"]
    force = "--force" in sys.argv

    if args:
        data = pd.read_csv(args[0])
    else:
        print("No CSV given - training on synthetic placeholder data (see make_synthetic_data).")
        print("Real usage: python train_decision_model.py path/to/simulink_export.csv\n")
        data = make_synthetic_data()

    trained, meets_targets = train(data)
    if meets_targets or force:
        save_model(trained)
    else:
        print("Not saved. Rule-based fallback in decision_layer.py remains active.")